#!/usr/bin/env ruby
# frozen_string_literal: true

require "thor"
require_relative "../lib/pullbox/mailmate"

class MailMateCLI < Thor
  desc "beta", "Updates MailMate to the latest beta release"
  def beta
    Pullbox::MailMate.beta_release
  end
end

MailMateCLI.start(ARGV)
