#!/usr/bin/env ruby
# frozen_string_literal: true

require "net/http"
require "nokogiri"
require "plist"
require_relative "../lib/pullbox/applescript"

mailmate = "/Applications/MailMate.app/Contents/Info.plist"
raise "MailMate not installed." unless File.exist? mailmate

result = Plist.parse_xml(mailmate)
raise "MailMate not properly installed." if result.nil?

regexp1 = /\(r(?<number>\d+)\)/i
regexp2 = /(?<number>\d+)/
long_version = result["CFBundleGetInfoString"]
version = long_version.match(regexp1)

doc = Nokogiri::HTML(Net::HTTP.get(URI("https://updates.mailmate-app.com/archives/")))
doc.xpath("(//table//tr//td/a)[last()]").each do |current_release|
  current_version = current_release.content.match(regexp2)

  if current_version[:number].to_i > version[:number].to_i
    Pullbox::AppleScript.display_dialog "Update available.\nVersion: #{current_version}", "MailMate"
  end
end
