#!/usr/bin/env ruby
# frozen_string_literal: true

require "English"
require "plist"
require_relative "../lib/pullbox/applescript"

mailmate = "/Applications/MailMate.app/Contents/Info.plist"
raise "MailMate not installed." unless File.exist? mailmate

result = Plist.parse_xml(mailmate)
raise "MailMate not properly installed." if result.nil?

long_version = result["CFBundleGetInfoString"]
version = long_version.match(/\(r(?<number>\d+)\)/i)
following_release = version[:number].to_i.next
search_string = "MailMate_r#{following_release}.tbz"

content = `curl -s https://updates.mailmate-app.com/archives/ | grep #{search_string}`

if !content.empty? && $CHILD_STATUS.exited?
  Pullbox::AppleScript.display_dialog "Update available.\nVersion: #{following_release}", "MailMate"
end
